<a href="https://colab.research.google.com/github/tarupathak30/Deep-Learning-/blob/main/ann_keras/regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8, 8, 4], [7, 9, 5], [6, 10, 6], [5, 12, 7]], columns=['cgpa', 'resume_score', 'lpa'])

In [3]:
df

cgpa  resume_score  lpa
0     8             8    4
1     7             9    5
2     6            10    6
3     5            12    7

In [8]:
import tensorflow
from tensorflow import keras
from keras import Sequential, Input
from keras.layers import Dense

In [9]:
model = Sequential([
    Input(shape=(2, )),
    Dense(2, activation='linear'),
    Dense(1, activation='linear')
])

In [10]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.get_weights()

[array([[-0.09214914, -1.2020935 ],
        [-0.0509938 , -0.13472676]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 1.2574047 ],
        [-0.43996793]], dtype=float32),
 array([0.], dtype=float32)]

In [12]:
new_weights = [np.array([[0.1, 0.1],
              [0.1, 0.1]], dtype=np.float32),
              np.array([0., 0.], dtype=np.float32),
              np.array([[0.1],
              [0.1]], dtype=np.float32),
              np.array([0.], dtype=np.float32)]

In [13]:
model.set_weights(new_weights)

In [15]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error', optimizer=optimizer)

In [16]:
model.fit(df.iloc[:, 0:-1].values, df['lpa'].values, epochs=75, verbose=1, batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 25.6371 
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 28.3817
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 27.5307 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 28.5573 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 20.7283 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 25.0478
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 24.6901
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 29.1999
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 31.0525
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 21.9181  
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 28.0134  
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 23.4501 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 28.6615 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 19.0583 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 20.5247
Epoch 16/75
4/

In [17]:
model.get_weights()

[array([[0.3737147 , 0.3737147 ],
        [0.36570102, 0.36570102]], dtype=float32),
 array([0.27240548, 0.27240548], dtype=float32),
 array([[0.3730175],
        [0.3730175]], dtype=float32),
 array([0.20480092], dtype=float32)]